### ISSUE TITLE
Web validator crashes (uncaught exception) for specific file

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-Validator#180]
While working on the UnityGltf exporter (using the validator to check if resulting files are corrrect) I somehow managed to produce a file that
- works in model-viewer / three.js
- crashes the validator.

I can only assume that it's _really really_ broken, but it would be better if Validator could tell me in which way.

To reproduce, 
- download [validatorException.zip](https://github.com/KhronosGroup/glTF-Validator/files/8566770/validatorException.zip), unpack
- drag "todo (1).glb" into https://github.khronos.org/glTF-Validator/
- Expected: shows a horrible list of issues with this file
- Actual: nothing happens, stuck at "Validating..."

This appears in the browser console:
```
Uncaught Instance of 'minified:d5'
    at Object.c (https://github.khronos.org/glTF-Validator/scripts/validator.dart.js:315:3)
    at i.a8 (https://github.khronos.org/glTF-Validator/scripts/validator.dart.js:8614:9)
    at i.a3 (https://github.khronos.org/glTF-Validator/scripts/validator.dart.js:8624:23)
    at fb.dZ (https://github.khronos.org/glTF-Validator/scripts/validator.dart.js:9869:72)
    at tear_off.<anonymous> (https://github.khronos.org/glTF-Validator/scripts/validator.dart.js:437:65)
    at n3.eI (https://github.khronos.org/glTF-Validator/scripts/validator.dart.js:6250:21)
    at n3.dd (https://github.khronos.org/glTF-Validator/scripts/validator.dart.js:6254:21)
    at eh.b1 (https://github.khronos.org/glTF-Validator/scripts/validator.dart.js:6165:5)
    at di.d5 (https://github.khronos.org/glTF-Validator/scripts/validator.dart.js:6208:9)
    at n1.$0 (https://github.khronos.org/glTF-Validator/scripts/validator.dart.js:6227:3)
```

When dragging the file into https://modelviewer.dev/editor/, it actually has the content that it should have (and _seems_ to be fine), but there the red "ERROR" button actually contains a long list of validation issues.

**Comment by lexaknyazev** [comment]
Thanks for the repro case!

The file surprisingly generates too many (over 16384) validation errors while parsing the GLB container. Apparently, there's no exception handler for this case.

I'll investigate and release an updated build ASAP.

**Comment by hybridherbst** [comment]
Wow, I guess that might get a record for "most issues in a file that still somehow works fine" 😁
Thanks!

**Comment by lexaknyazev** [comment]
The GLB file has extra 178476 trailing zero bytes that confuse the validator. This will be fixed soon.

**Comment by lexaknyazev** [comment]
The GLB spec does not forbid trailing bytes. For example, apps could put there a checksum for additional integrity. Viewers most likely just ignore that. The upcoming validator release warns that extra bytes are present.

By the way, the file above has a fair amount of other issues.

**Comment by hybridherbst** [comment]
Thanks - 
yes, the file definitely has, I was in the middle of some exporter refactoring (and exactly why I wanted to check with the validator).

**Comment by lexaknyazev** [comment]
The web version has been updated.
