### ISSUE TITLE
spectacularly screwed-up glTF JSON yields validator stack trace

### ISSUE THREAD

**Issue by zellski** [KhronosGroup/glTF-Validator#66]
This is not urgent, but I'm throwing a lot of really terrible glTF at the validator, and it turns out if your JSON includes:
```json
{
  "materials": [[ ]],
}
```
then the validator just breaks down and weeps:
```
Unhandled exception:
NoSuchMethodError: The method 'link' was called on null.
Receiver: null
Tried calling: link(Instance of 'Gltf', Instance of 'Context')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      new Gltf.fromMap.linkCollection.<anonymous closure> (package:gltf/src/base/gltf.dart:242:14)
#2      SafeList.forEachWithIndices (package:gltf/src/utils.dart:675:13)
#3      new Gltf.fromMap.linkCollection (package:gltf/src/base/gltf.dart:240:12)
#4      new Gltf.fromMap (package:gltf/src/base/gltf.dart:267:19)
#5      GltfJsonReader.read.<anonymous closure> (package:gltf/src/gltf_reader.dart:120:28)
#6      _SimpleCallbackSink.close (dart:convert/chunked_conversion.dart:58)
#7      _JsonUtf8DecoderSink.close (dart:convert-patch/dart:convert/convert_patch.dart:1817)
#8      GltfJsonReader._onDone (package:gltf/src/gltf_reader.dart:156:17)
#9      _RootZone.runGuarded (dart:async/zone.dart:1304)
#10     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:383)
#11     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:393)
#12     _DelayedDone.perform (dart:async/stream_impl.dart:597)
#13     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
#14     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#17     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:112)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by lexaknyazev** [comment]
Embarrassing. `2.0.0-dev.1.7` branch contains the fix. Please continue throwing terrible glTF at the validator.
